### ISSUE TITLE
Reworked neptune for TT03p5

### ISSUE THREAD

**Issue by psychogenic** [TinyTapeout/tinytapeout-03p5#12]
Have a 1x1 for inclusion:

https://github.com/psychogenic/tt03p5_neptune_proportional_b

Reworked to leverage the extra I/O (using bidirs as outputs), added a number of higher clock speed options for testing, and improved the algorithm a good deal from tt03.

**Comment by urish** [comment]
Welcome aboard!

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/1607d0bd-af4f-4406-a63a-4ba669800b1e)

**Comment by psychogenic** [comment]
so cool :D
