### ISSUE TITLE
gatecat FPGA

### ISSUE THREAD

**Issue by psychogenic** [TinyTapeout/tinytapeout-03p5#14]
Second FPGA repo Matt wanted migrated.

Did the basic work, but this one's even worse than the s4ga--no testing present at all, not sure how to handle or if we just include as-is (has a lot of direct PDK inclusions)

https://github.com/psychogenic/tt03p5-gatecat-fpga

**Comment by psychogenic** [comment]
This one is failing STA/has setup violations.

**Comment by mattvenn** [comment]
STA could maybe be fixed by just reducing the clock period in the config.tcl.
https://github.com/gatecat/tt02-fpga-respin/blob/main/src/config.tcl

the original clock period is huge

**Comment by psychogenic** [comment]
Ok, goes green @ 20MHz.
Still no actual tests in there, so dunno if I messed something up. but GDS is good, it's green on a 1x2 tile.
https://github.com/psychogenic/tt03p5-gatecat-fpga/actions
