### ISSUE TITLE
TOTP authenticator

### ISSUE THREAD

**Issue by htfab** [TinyTapeout/tinytapeout-03p5#15]
Please add https://github.com/htfab/totp/ to the shuttle.
It's an implementation of the TOTP algorithm (Google Authenticator, Aegis, Authy, Duo, FreeOTP etc.) in a 2x2 slot as discussed on discord. The documentation is missing at the moment, I intend to write it after the deadline.

**Comment by urish** [comment]
There you go:

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/7d235322-9ca1-45c7-898e-d74bbdda8371)
