### ISSUE TITLE
algofoogle's solo_squash VGA game submission for tt03p5

### ISSUE THREAD

**Issue by algofoogle** [TinyTapeout/tinytapeout-03p5#16]
G'day folks! If there's space, please include my 1x1 submission for tt03p5:
https://github.com/algofoogle/tt03p5-solo-squash

It's a *minimal* VGA game. I hope to sneak in some further improvements before the deadline, but this is otherwise good to go now.

Cheers, and good luck with the tt03p5 tapeout!

**Comment by urish** [comment]
solo_squash is in the house!

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/37c2341e-b30e-4084-8e22-b21339cf4b76)

**Comment by algofoogle** [comment]
Deeeelightful! That's a great looking rectangle. Thanks again Uri :) Love your work!
