### ISSUE TITLE
XLS APU Pulse Oscillator

### ISSUE THREAD

**Issue by proppy** [TinyTapeout/tinytapeout-03p5#18]
XLS APU pulse oscillator based on https://www.nesdev.org/wiki/APU_Pulse.

Didn't include the codegen as part of the CI as it caused issue last time, you can find an interactive version here:
https://colab.research.google.com/gist/proppy/72b51551ac736abbcfc4cadd51a9adeb/xls_audio_playground.ipynb

https://github.com/proppy/tt03p5-xls-apu

**Comment by urish** [comment]
Pulse's up!

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/ef8ff293-e3e4-446e-ad48-0d52e8fff9fe)
