### ISSUE TITLE
Add TrainLED2

### ISSUE THREAD

**Issue by cpldcpu** [TinyTapeout/tinytapeout-03p5#3]
Here is my port of TrainLED2 to TT3p5:

https://github.com/cpldcpu/tt03p5-TrainLED2

**Comment by urish** [comment]
@cpldcpu thanks! 

There's an issue with your top level module: the name of the output signal should be `uo_out`, not `ui_out`:

https://github.com/cpldcpu/tt03p5-TrainLED2/blob/3b8d0f7d0738054da39eeb5276ea2b4412e051b9/src/TrainLED2_top.v#L3

**Comment by cpldcpu** [comment]
Indeed. Strangely enough it still passed build?

**Comment by cpldcpu** [comment]
It's fixed now.

**Comment by urish** [comment]
There you go:

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/221045fa-db4f-49de-9520-19a6c6d2b2c5)

**Comment by cpldcpu** [comment]
cute!
