### ISSUE TITLE
Add M0

### ISSUE THREAD

**Issue by moyesw** [TinyTapeout/tinytapeout-03p5#4]
Here is my port of M0 to TT03p5:

https://github.com/moyesw/TT03p5-M0

**Comment by urish** [comment]
There you go:

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/bcf03862-7d9b-4bee-9448-37c14787fe3b)

**Comment by moyesw** [comment]
Gate level tests also pass
![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/116853609/036ebf30-a345-4a4d-8f08-c8018e79d380)

**Comment by urish** [comment]
Hello world! ABC
