### ISSUE TITLE
Add balanced ternary program counter and radix converter

### ISSUE THREAD

**Issue by aiunderstand** [TinyTapeout/tinytapeout-03p5#6]
https://github.com/aiunderstand/tt03p5-4-trit-balanced-ternary-counter-bt_signb_bt-radix-convertor

**Comment by urish** [comment]
Welcome on chip!

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/e6146611-5533-4f0c-bb64-e14175819088)

**Comment by aiunderstand** [comment]
Thanks for the confirmation Uri!
