### ISSUE TITLE
LED Panel Driver submission

### ISSUE THREAD

**Issue by TomKeddie** [TinyTapeout/tinytapeout-03p5#8]
Please add https://github.com/TomKeddie/tinytapeout-2023-2a (git@github.com:TomKeddie/tinytapeout-2023-2a.git) to 3p5 if there is space. 

Thanks for running this.

**Comment by urish** [comment]
There you go:

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/73ea19eb-fc0a-4cea-9745-059836f94a6d)
