### ISSUE TITLE
My entry to TT03p5

### ISSUE THREAD

**Issue by shaos** [TinyTapeout/tinytapeout-03p5#9]
https://github.com/shaos/tt03p5-submission-shaos

**Comment by urish** [comment]
There you go:

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/5e06edad-bcc7-4786-b67c-a52256c8f045)

**Comment by shaos** [comment]
Does it mean it's empty? ;)

**Comment by urish** [comment]
It means it's tiny :)

pretty much matches what you see in the [GDS render from your repo's action](https://github.com/shaos/tt03p5-submission-shaos/actions/runs/5149276387#summary-13940101867):

![image](https://github.com/TinyTapeout/tinytapeout-03p5/assets/892318/f2a74b60-f213-4415-91cf-2b3ef64666c6)
